language: node_js
node_js:
  - "6"
before_script:
  - npm install -g gulp
script: 
  - gulp build --production
deploy:
  provider: heroku
  skip_cleanup: true
  api_key: $HEROKU_KEY
  app: $HEROKU_APP